{% set name = "gin-config" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c6ea5026ded927c8c93c990b01c695257c1df446e45e549a158cfbc79e19ed6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six >=1.10.0
  run_constrained:
    - tensorflow >=1.13.0

test:
  imports:
    - gin

about:
  home: https://github.com/google/gin-config
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Gin-Config: A lightweight configuration library for Python'
  doc_url: https://github.com/google/gin-config/blob/master/docs/index.md
  dev_url: https://github.com/google/gin-config

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
