{% set name = "gin-config" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9499c060e1faa340959fc4ada7fe53f643d6f8996a80262b28a082c1ef6849de

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six >=1.10.0
  run_constrained:
    - tensorflow >=1.13.0

test:
  imports:
    - gin

about:
  home: https://github.com/google/gin-config
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Gin-Config: A lightweight configuration library for Python'
  doc_url: https://github.com/google/gin-config/blob/master/docs/index.md
  dev_url: https://github.com/google/gin-config

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
